name: Init ci for node with Checkout and pnmp

on:
  workflow_call:


jobs:
  init-node:
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

