name: Reusable workflow example

on:
  workflow_call:

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Init node
      uses: ./.github/actions/init.yml
    - name: Run tests
      run: pnpm test

