name: Reusable workflow example

on:
  workflow_call:

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: |
          - recursive: true
            args: [--no-frozen-lockfile]
#    - name: Init node
#      uses: ./.github/actions/init.yml
    - name: Run tests
      run: pnpm test

